for def in HAVE_ACCL_VERBS HAVE_DC HAVE_ENDIAN HAVE_EX_ODP HAVE_GID_ATTR HAVE_IPV4_EXT HAVE_IPV6 HAVE_MASKED_ATOMICS HAVE_PACKET_PACING_EXP HAVE_RAW_ETH HAVE_RAW_ETH_EXP HAVE_RSS_EXP HAVE_SCATTER_FCS HAVE_VERBS_EXP HAVE_XRCD; do
  unifdef -m -D$def *.c
  unifdef -m -D$def *.h
done
